apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.data.pvcName }}
  labels:
    {{- include "sftpgo.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  # RWX : monté par SFTPGo, Samba (partage sftp) et le nettoyage
  accessModes: ["ReadWriteMany"]
  storageClassName: {{ .Values.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-etat
  labels:
    {{- include "sftpgo.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.state.storageClass }}
  resources:
    requests:
      storage: {{ .Values.state.size }}
