apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formbricks-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: formbricks-tls-certs
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: formbricks-webapp
            port:
              number: 3000
