apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prestashop.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prestashop.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-root-password: {{ .Values.mariadb.dbRootPassword | quote }}
  db-password: {{ .Values.mariadb.dbPassword | quote }}
  admin-password: {{ .Values.prestashop.adminPassword | quote }}
