---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
  namespace: guacamole
  labels:
    app.kubernetes.io/part-of: guacamole
    app.kubernetes.io/component: web
data:
  GUACD_HOSTNAME: guacd.guacamole.svc.cluster.local
  GUACD_PORT: "4822"
  POSTGRESQL_HOSTNAME: guacamole-postgresql.guacamole.svc.cluster.local
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_DATABASE: guacamole_db
  POSTGRESQL_AUTO_CREATE_ACCOUNTS: "true"
  LDAP_HOSTNAME: "192.168.0.100"
  LDAP_PORT: "389"
  LDAP_ENCRYPTION_METHOD: "none"
  LDAP_USER_BASE_DN: "DC=corp,DC=lcl"
  LDAP_USERNAME_ATTRIBUTE: "sAMAccountName"
  LDAP_GROUP_BASE_DN: "OU=Technical,OU=groups,OU=CORP,DC=corp,DC=lcl"
  LDAP_GROUP_NAME_ATTRIBUTE: "cn"
  LDAP_MEMBER_ATTRIBUTE: "member"
  LDAP_USER_SEARCH_FILTER: "(&(objectClass=user)(sAMAccountName=*))"
  LDAP_GROUP_SEARCH_FILTER: "(objectClass=group)"
  LDAP_MEMBER_ATTRIBUTE_TYPE: "dn"
  LDAP_DEREFERENCE_ALIASES: "never"
  LDAP_MAX_SEARCH_RESULTS: "1000"
  LDAP_FOLLOW_REFERRALS: "false"
  REMOTE_IP_VALVE_ENABLED: "true"
  RECORDING_ENABLED: "true"
  RECORDING_SEARCH_PATH: /var/lib/guacamole/recordings
  TOTP_ENABLED: "true"
  TOTP_ISSUER: "Guacamole"
  TOTP_DIGITS: "6"
  TOTP_PERIOD: "30"
  TOTP_MODE: "sha1"
