---
apiVersion: v1
kind: Secret
metadata:
  name: guacamole-db-credentials
  namespace: guacamole
  labels:
    app.kubernetes.io/part-of: guacamole
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_DB: guacamole_db
  POSTGRES_USER: guacamole
  POSTGRES_PASSWORD: "Gu4c-Pg!r7Kz9Qw2"
---
apiVersion: v1
kind: Secret
metadata:
  name: guacamole-ldap-credentials
  namespace: guacamole
  labels:
    app.kubernetes.io/part-of: guacamole
    app.kubernetes.io/component: ldap
type: Opaque
stringData:
  LDAP_SEARCH_BIND_DN: "CN=s_guacamole,OU=service_accounts,OU=CORP,DC=corp,DC=lcl"
  LDAP_SEARCH_BIND_PASSWORD: "YcJVZOpl8boCDn9C2M2o"
