apiVersion: apps/v1
kind: Deployment
metadata:
  name: typebot-postgres
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typebot-postgres
  template:
    metadata:
      labels:
        app: typebot-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.images.postgres }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.db }}
            # AJOUT DE CETTE LIGNE POUR REDIRIGER LE STOCKAGE DANS UN SOUS-DOSSIER
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: typebot-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: typebot-postgres
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: typebot-postgres
