apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: typebot-postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 10Gi
