apiVersion: v1
kind: Secret
metadata:
  name: typebot-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@typebot-postgres:5432/{{ .Values.postgresql.db }}"
  ENCRYPTION_SECRET: "{{ .Values.encryptionSecret }}"
  NEXTAUTH_SECRET: "{{ .Values.encryptionSecret }}"
  ADMIN_EMAIL: "{{ .Values.adminEmail }}"
  SMTP_HOST: "typebot-mailpit"
  SMTP_PORT: "1025"
  NEXT_PUBLIC_SMTP_FROM: "admin@xixtu.eu"
  ADMIN_EMAIL: "admin@xixtu.eu"
