apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "collectd-exporter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "collectd-exporter.selector" . | nindent 4 }}
  ports:
    - name: http
      port: 9103
      targetPort: http
