{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "collectd-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "collectd-exporter.selector" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      # label instance = nom de la borne (Hostname collectd), à garder
      honorLabels: true
{{- end }}
