---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: guacamole
  labels:
    app.kubernetes.io/name: guacd
    app.kubernetes.io/part-of: guacamole
    app.kubernetes.io/component: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guacd
      app.kubernetes.io/part-of: guacamole
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guacd
        app.kubernetes.io/part-of: guacamole
        app.kubernetes.io/component: proxy
    spec:
      containers:
        - name: guacd
          image: guacamole/guacd:1.6.0
          ports:
            - containerPort: 4822
              name: guacd
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 10
            periodSeconds: 30
